### ISSUE TITLE
[Bug] Vega 56 (gfx900) — ZLUDA fails to initialize CUDA device, nvcuda.dll dependency error

### ISSUE THREAD

**Issue by eviscerations** [patientx/ComfyUI-Zluda#463]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

ComfyUI-Zluda launches and detects the Vega 56 (gfx900) as a CUDA device via ZLUDA, allowing GPU-accelerated inference.

### Actual Behavior

ZLUDA fails to initialize. nvcuda.dll dependency error on comfyui.bat, nccl.dll not found error on comfyui-n.bat. CUDA device detected: None. Application crashes at startup with RuntimeError: No CUDA GPUs are available.

### Steps to Reproduce

1. Install ComfyUI-Zluda following the HIP 6.2.4 path on a system with AMD Radeon RX Vega 56 (gfx900)
2. Install gfx900 rocBLAS libraries from YellowRoseCx/koboldcpp-rocm deps-v6.2.0
3. Confirm all zluda DLLs present including nccl.dll and nvcuda.dll
4. Run comfyui-n.bat or comfyui.bat
5. Observe CUDA device: None and RuntimeError: No CUDA GPUs are available

### Debug Logs

```powershell
-----------------------------------------------------------------------
* COMFYUI-ZLUDA INSTALL (for HIP 6.2.4 / 6.4.2 with MIOPEN and Triton)*
-----------------------------------------------------------------------

 ::  - Setting up the virtual environment
 ::  - Virtual environment activation
 ::  - Updating the pip package
 ::  Beginning installation ...
 ::  - Installing required packages
 ::  - Installing torch for AMD GPUs (First file is 2.7 GB, please be patient)
 ::  - Installing onnxruntime (required by some nodes)
 ::  - (temporary numpy fix)
 ::  - Detecting Python version and installing appropriate triton package
 ::  - Detected Python 3.10
 ::  - WARNING: Unsupported Python version 3.10, skipping triton installation
 ::  - Full version info: Python 3.10.11
 ::  - ZLUDA 3.9.5 nightly patched for HIP SDK 6.2.4 / 6.4.2 with miopen and triton-flash attention.
*** Installation is completed in 00:02:41.39

zluda directory contents confirmed:
cublas.dll, cublasLt.dll, cudnn.dll, cufft.dll, cufftw.dll, cusparse.dll,
nccl.dll, nvcuda.dll (10,225,152 bytes), nvml.dll, nvrtc.dll,
zluda.exe, zluda_dump.dll, zluda_redirect.dll — all present

--- comfyui-n.bat output ---

WARNING: You need pytorch with cu130 or higher to use optimized CUDA operations.
Found comfy_kitchen backend triton: {'available': False, 'disabled': True, 'unavailable_reason': "ImportError: No module named 'triton'"}
Found comfy_kitchen backend eager: {'available': True, 'disabled': False}
Found comfy_kitchen backend cuda: {'available': False, 'disabled': True, 'unavailable_reason': 'CUDA not available on this system'}

  ::  ZLUDA: Triton not installed
  ::  CUDA device detected: None

Traceback (most recent call last):
  File "main.py", line 206, in <module>
    import execution
  File "execution.py", line 17, in <module>
    import comfy.model_management
  File "comfy/model_management.py", line 255, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "comfy/model_management.py", line 205, in get_torch_device
    return torch.device(torch.cuda.current_device())
RuntimeError: No CUDA GPUs are available

--- comfyui.bat output ---

[INFO] AMD Software version: 26.1.1
[INFO] ZLUDA version: 3.9.5 ERROR: Could not load DLL: Could not find module
'[install path]\zluda\nvcuda.dll' (or one of its dependencies).
Try using the full path with constructor syntax.

  ::  PyTorch RMSNorm found, no patch needed.
  ::  CUDA device detected: None

Found comfy_kitchen backend cuda: {'available': False, 'disabled': True, 'unavailable_reason': 'CUDA not available on this system'}

Traceback (most recent call last):
  File "main.py", line 206, in <module>
    import execution
  File "execution.py", line 17, in <module>
    import comfy.model_management
  File "comfy/model_management.py", line 255, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "comfy/model_management.py", line 205, in get_torch_device
    return torch.device(torch.cuda.current_device())
RuntimeError: No CUDA GPUs are available
```

### Other

# [Bug] Vega 56 (gfx900) — ZLUDA fails to initialize CUDA device, nvcuda.dll dependency error

## Summary

Complete install of ComfyUI-Zluda following the HIP 6.2.4 path produces a correct installation but ZLUDA fails to present the GPU as a CUDA device at runtime. The application crashes at startup with `RuntimeError: No CUDA GPUs are available`. Both `comfyui-n.bat` and `comfyui.bat` launchers exhibit the same behavior.

---

## System

| Component | Detail |
|---|---|
| GPU | AMD Radeon RX Vega 56 |
| GPU architecture | GCN 5.0 / gfx900 |
| VRAM | 8GB HBM2 |
| CPU | AMD Ryzen 7 2700X |
| RAM | 32GB DDR4 |
| OS | Windows 10 22H2 |
| AMD driver | Adrenalin 26.1.1 (released 2026-01-21, WHQL) |
| HIP SDK | 6.2.4 |
| ZLUDA version | 3.9.5 nightly (patched by install-n.bat) |
| Python | 3.10.11 |
| ComfyUI-Zluda branch | master (hash: debf1835, 2026-05-17) |

---

## Install path followed

1. Installed HIP SDK 6.2.4 from AMD ROCm Hub (Windows 10 & 11)
2. Set system environment variables: `HIP_PATH` and `HIP_PATH_62` both pointing to `C:\Program Files\AMD\ROCm\6.2\`, `C:\Program Files\AMD\ROCm\6.2\bin` added to system `PATH`
3. Downloaded and extracted Google Drive addon package into `C:\Program Files\AMD\ROCm\6.2\` (overwriting existing files)
4. Backed up original `rocblas\library` contents
5. Installed gfx900 rocBLAS library files from `rocblas6.2.0-librarywith906.7z` (YellowRoseCx/koboldcpp-rocm deps-v6.2.0) into `C:\Program Files\AMD\ROCm\6.2\bin\rocblas\library\`
6. Added Windows Defender folder exclusion for the ComfyUI-Zluda directory (required — without this, the install script's ZLUDA zip download is quarantined as `Trojan:Win32/Poma!rfn`)
7. Ran `install-n.bat` — completed successfully in ~15 minutes
8. Confirmed `zluda\nccl.dll` and all expected ZLUDA files present after install

---

### comfyui-n.bat

```
[ERROR] Detected ZLUDA version: expected ERROR: Could not call zluda_get_nightly_flag:
function 'zluda_get_nightly_flag' not found, but nccl.dll is missing.
Likely blocked by AV as false positive.
...
::  CUDA device detected: None
RuntimeError: No CUDA GPUs are available
```

Note: nccl.dll was confirmed present in the zluda directory. The error message appears to be a false report — the real problem is ZLUDA failing to initialize.

### comfyui.bat

```
[INFO] ZLUDA version: 3.9.5 ERROR: Could not load DLL: Could not find module
'F:\...\ComfyUI-Zluda\zluda\nvcuda.dll' (or one of its dependencies).
Try using the full path with constructor syntax.
...
::  CUDA device detected: None
RuntimeError: No CUDA GPUs are available
```

nvcuda.dll is present in the zluda directory (10,225,152 bytes). The error indicates a missing dependency of nvcuda.dll itself, not the file being absent. This suggests ZLUDA's CUDA compatibility layer cannot initialize on gfx900.

---

## zluda directory contents (confirmed present)

```
cublas.dll         247,296 bytes
cublasLt.dll       185,856 bytes
cudnn.dll          260,608 bytes
cufft.dll          190,976 bytes
cufftw.dll         142,336 bytes
cusparse.dll       210,944 bytes
nccl.dll           121,344 bytes
nvcuda.dll      10,225,152 bytes
nvml.dll           157,696 bytes
nvrtc.dll          142,336 bytes
zluda.exe          300,032 bytes
zluda_dump.dll   8,621,568 bytes
zluda_redirect.dll 190,976 bytes
```

---

## rocBLAS library (confirmed present for gfx900)

gfx900-specific files were found and installed from the YellowRoseCx koboldcpp-rocm deps-v6.2.0 release, including:

- `Kernels.so-000-gfx900.hsaco`
- `TensileLibrary_lazy_gfx900.dat`
- Multiple `TensileLibrary_Type_*_gfx900.*` kernel and data files

These were not present in the original HIP SDK 6.2.4 install (which contained gfx906, gfx1030, gfx1100, gfx1101, gfx1102, gfx1151 only). The gfx900 files were sourced from the koboldcpp-rocm deps and installed per the likelovewant repository guidance for unsupported cards.

---

## install-n.bat output (relevant excerpt)

```
::  14:19:41  ::  - Detected Python 3.10
::  14:19:41  ::  - WARNING: Unsupported Python version 3.10, skipping triton installation
...
::  14:19:47  ::  - ZLUDA 3.9.5 nightly patched for HIP SDK 6.2.4 / 6.4.2 with miopen and triton-flash attention.
*** Installation is completed in 00:02:41.39
```

Triton skipped due to Python 3.10 (requires 3.12). Torch patched successfully. ZLUDA patched successfully.

---

## Runtime output (relevant excerpt, comfy_kitchen backends)

```
Found comfy_kitchen backend triton: {'available': False, 'disabled': True,
  'unavailable_reason': "ImportError: No module named 'triton'"}
Found comfy_kitchen backend eager: {'available': True, 'disabled': False}
Found comfy_kitchen backend cuda: {'available': False, 'disabled': True,
  'unavailable_reason': 'CUDA not available on this system'}
```

---

## Additional context

The gfx900 (Vega/Fiji generation) architecture predates RDNA. HIP SDK 6.2.4 does not ship rocBLAS libraries for gfx900 natively — these had to be sourced separately. It is unclear whether ZLUDA 3.9.5 supports gfx900 at all, or whether the `nvcuda.dll` dependency failure is specific to this architecture.

The install-n.bat path was followed as it is the current recommended install method. The install-legacy.bat path (HIP 5.7.1) was not tested.

---

## Questions

1. Is gfx900 (Vega 56) a supported architecture for ComfyUI-Zluda with HIP 6.2.4?
2. Is the `nvcuda.dll` dependency failure on comfyui.bat a known issue with GCN5 architecture?
3. Would the install-legacy.bat (HIP 5.7.1) path have better gfx900 compatibility?
4. Are there any flags or workarounds to force ZLUDA to initialize on gfx900?

---

## Related

- Issue #346 — "Recent changes to torch compiling break compatibility with older GPUs" (filed by nota-rudveld, Vega 56, resolved in PR #347 and merged Oct 22, 2025)
- PR #347 — version compatibility fix for Vega 56, confirmed working on gfx900 per the submitter

This issue appears distinct from #346/#347 — the torch version check issue is resolved, but ZLUDA itself is not initializing the GPU.

**Comment by patientx** [comment]
I don't have any access / a way to test those gpu's, your best bet would be to try legacy 5.7.1

**Comment by TheFerumn** [comment]
It should 100% work on 5.7.1 if you have custom rocBLAS library. I am using even older gfx803 without issues. You honestly don't need HIP SDK 6.2.4 because it provides no advantage to your GPU at all. You can't use any of newest optimizations anyway even if you will make it work on 6.2.4

**Comment by eviscerations** [comment]
Thanks @patientx and @TheFerumn — appreciate the pointers. Confirming for the record on gfx900 (Vega 56), since this trips people up:

**For inference / getting ZLUDA to initialize: the advice is correct.** Reverting to HIP SDK **5.7.1** + a custom gfx900 rocBLAS library gets ZLUDA initializing cleanly (`torch.cuda.is_available() → True`, detected as `Radeon RX Vega [ZLUDA]`). And 6.2.4 adds nothing for legacy GCN — agreed, no reason to chase it.

**For training (kohya_ss LoRA), that same working config still doesn't get there.** With 5.7.1 + the custom gfx900 rocBLAS (so detection/init are fine), training fails two ways:
- VAE encode → `RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED` on `cublasSgemm` (first float32 GEMM in the loop), and
- with latents pre-cached to disk to skip the VAE, the U-Net forward pass **hangs silently at step 0** — no error, no GPU activity.

That's consistent with gfx900 Tensile kernel coverage being incomplete (~25%): inference exercises a subset of GEMM configs that the custom rocBLAS covers; training exercises a superset (incl. the backward pass) that currently isn't there. So **"works on 5.7.1 with custom rocBLAS" holds for inference, not for training** on this arch.

**TL;DR for others on gfx900/gfx803:** ZLUDA on Windows = good for inference, not currently viable for LoRA training. If you need training on these GPUs, native **Linux + ROCm** (`HSA_OVERRIDE_GFX_VERSION=9.0.0`) is the confirmed path; otherwise RDNA-class hardware.

Full write-up of the attempts + exact error signatures, if it helps anyone: https://github.com/eviscerations/comfyui-rinsei

**Comment by LtLazlow** [comment]
I'm trying to get this to work on my Radeon RX Vega 56. The HIP 6.2.4 version indeed has the `CUDA device detected: None.` error.

But the HIP 5.7.1 version fails to start:
```
@torch.library.custom_op("comfy_kitchen::adaln", mutates_args=())
     ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'torch.library' has no attribute 'custom_op'
```

@eviscerations how did you get it working on your Vega 56?

**Comment by TheFerumn** [comment]
<img width="1814" height="609" alt="Image" src="https://github.com/user-attachments/assets/848602bb-4d9e-4e14-8ae2-6259f640c7d5" />
This is the fix for it i have in my cloned repository. Comfy Kitchen doesn't work with older torch versions but joyimage trying to force it even if you are not needing it.
