### ISSUE TITLE
AttributeError: module 'torch.library' has no attribute 'custom_op'

### ISSUE THREAD

**Issue by dietvatten** [patientx/ComfyUI-Zluda#412]
After todays commit which added Comfy-kitchen i'm getting errors and can't get it to start.

```
HIP_PATH = C:\Program Files\AMD\ROCm\6.2\
HIP_PATH_57 = C:\Program Files\AMD\ROCm\5.7\
HIP_PATH_62 = C:\Program Files\AMD\ROCm\6.2\

[INFO] Detected Git version: 2.46.0.windows.1
[INFO] ComfyUI-Zluda current path: C:\ComfyUI-Zluda\
[INFO] ComfyUI-Zluda current version: 2026-01-07 13:28:32 hash: dc1ba3bb branch: master
[INFO] Checking and updating to a new version if possible...
[INFO] Already up to date.

[INFO] AMD Software version: 24.12.1
[INFO] ZLUDA version: 3.8.4 ERROR: Could not call zluda_get_nightly_flag: function 'zluda_get_nightly_flag' not found
[INFO] Launching application via ZLUDA...

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2026-01-07 18:33:37.177
** Platform: Windows
** Python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
** Python executable: C:\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: C:\ComfyUI-Zluda
** ComfyUI Base Folder Path: C:\ComfyUI-Zluda
** User directory: C:\ComfyUI-Zluda\user
** ComfyUI-Manager config path: C:\ComfyUI-Zluda\user\default\ComfyUI-Manager\config.ini
** Log path: C:\ComfyUI-Zluda\user\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\ComfyUI-Zluda\custom_nodes\ComfyUI-Easy-Use
   0.0 seconds: C:\ComfyUI-Zluda\custom_nodes\rgthree-comfy
   3.8 seconds: C:\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Warning, you are using an old pytorch version and some ckpt/pt files might be loaded unsafely. Upgrading to 2.4 or above is recommended as older versions of pytorch are no longer supported.

  ::  Checking package versions...
Found pydantic: 2.11.5, pydantic-settings: 2.9.1
  ::  Pydantic packages are compatible, skipping reinstall
Installed version of comfyui-frontend-package: 1.35.9
Installed version of comfyui-workflow-templates: 0.7.67
Installed version of av: 14.3.0
Installed version of comfyui-embedded-docs: 0.3.1
Installed version of comfy-kitchen: 0.2.3
  ::  Package version check complete.
  ::  PyTorch RMSNorm not found, adding ComfyUI-compatible layer.
  ::  ComfyUI-compatible RMSNorm layer installed.

***----------------------ZLUDA-----------------------------***
  ::  Patching ONNX Runtime for ZLUDA — disabling CUDA EP.
  ::  ZLUDA detected, disabling non-supported functions.
  ::  CuDNN, flash_sdp, mem_efficient_sdp disabled.
  ::  Using ZLUDA with device: AMD Radeon RX 7900 XTX [ZLUDA]
***--------------------------------------------------------***

Total VRAM 24560 MB, total RAM 31887 MB
pytorch version: 2.3.0+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 7900 XTX [ZLUDA] : native
Please update pytorch to use native RMSNorm
Torch version too old to set sdpa backend priority.
Traceback (most recent call last):
  File "C:\ComfyUI-Zluda\main.py", line 177, in <module>
    import execution
  File "C:\ComfyUI-Zluda\execution.py", line 16, in <module>
    from latent_preview import set_preview_method
  File "C:\ComfyUI-Zluda\latent_preview.py", line 4, in <module>
    from comfy.taesd.taesd import TAESD
  File "C:\ComfyUI-Zluda\comfy\taesd\taesd.py", line 10, in <module>
    import comfy.ops
  File "C:\ComfyUI-Zluda\comfy\ops.py", line 488, in <module>
    from .quant_ops import (
  File "C:\ComfyUI-Zluda\comfy\quant_ops.py", line 5, in <module>
    import comfy_kitchen as ck
  File "C:\ComfyUI-Zluda\venv\lib\site-packages\comfy_kitchen\__init__.py", line 3, in <module>
    from .backends import cuda as _cuda_backend  # noqa: F401
  File "C:\ComfyUI-Zluda\venv\lib\site-packages\comfy_kitchen\backends\cuda\__init__.py", line 94, in <module>
    from comfy_kitchen.backends.eager.quantization import DTYPE_TO_CODE  # noqa: E402
  File "C:\ComfyUI-Zluda\venv\lib\site-packages\comfy_kitchen\backends\eager\__init__.py", line 11, in <module>
    from .quantization import (
  File "C:\ComfyUI-Zluda\venv\lib\site-packages\comfy_kitchen\backends\eager\quantization.py", line 201, in <module>
    @torch.library.custom_op("comfy_kitchen::quantize_fp8", mutates_args=())
AttributeError: module 'torch.library' has no attribute 'custom_op'
Press any key to continue . . . 
```

**Comment by patientx** [comment]
I think it won't work with torch 2.3. I will remove kitchen from the "old" zluda BUT it seems more and more stuff will start requiring that.

I don't have a solution for the really old gpu's but people over 6000 should be using the new setup already to avoid this.

EDIT : I removed comfy-kitchen to be auto installed , you would also need to uninstall it for the time being ; run the file I added in the main folder: "comfy-kitchen-remove.bat" by double clicking on it.

**Comment by dietvatten** [comment]
Thanks a ton!

I'll keep going with this old setup for a while and then switch to the new one once i have everything sorted.

**Comment by umpaumpa** [comment]
> I think it won't work with torch 2.3. I will remove kitchen from the "old" zluda BUT it seems more and more stuff will start requiring that.
> 
> I don't have a solution for the really old gpu's but people over 6000 should be using the new setup already to avoid this.
> 
> EDIT : I removed comfy-kitchen to be auto installed , you would also need to uninstall it for the time being ; run the file I added in the main folder: "comfy-kitchen-remove.bat" by double clicking on it.

It's a bit sadder: if you delete this folder, FP8/FP4 issues arise.

```

Total VRAM 25368 MB, total RAM 24469 MB
pytorch version: 2.3.0+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon(TM) Graphics [ZLUDA] : native
Enabled pinned memory 11010.0
Please update pytorch to use native RMSNorm
Torch version too old to set sdpa backend priority.
comfy_kitchen: ZLUDA mode - FP8/FP4 disabled
Failed to import comfy_kitchen, Error: No module named 'comfy_kitchen.tensor', fp8 and fp4 support will not be available.
Using split optimization for attention
No comfy kitchen, using old apply_rope functions.
```

**Comment by jin-eld** [comment]
Sorry for commenting on a closed issue; if usage of `custom_op` could somehow be made optional, that'd be great. Some really GPU poor folks on MI25 Instinct cards can't update torch anymore, stuck with 2.3, previous ComfyUI versions was one of the few things that actually worked on these cards 😅 

I know, that support of old stuff becomes unsustainable at some point, so just asking if it's doable to prolong the inevitable for the time being or if the `custom_op` thing is a new requirement which can't be reasonably worked around?

**Comment by patientx** [comment]
if I could I would trust me. Before this kitchen stuff there was no problem using comfy with older gpu's. I am not a programmer sadly and if anyone can work on it I would add it here gladly.

**Comment by sca255** [comment]
@patientx i have a rx 580 2048 sp why is more recent troch unsuitable for these old gpus , what is the reason?
